package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libjsonnet",
    hdrs = ["libjsonnet.h"],
    includes = ["."],
)

cc_library(
    name = "libjsonnet_fmt",
    hdrs = ["libjsonnet_fmt.h"],
    includes = ["."],
)

cc_library(
    name = "libjsonnet++",
    hdrs = ["libjsonnet++.h"],
    includes = ["."],
)
